[workspace]
resolver = "2"
members = [
    "scopegraphs-lib",
    "scopegraphs",
    "scopegraphs-macros",
    "scopegraphs-regular-expressions",
]
default-members = [
    "scopegraphs",
    "scopegraphs-lib",
    "scopegraphs-macros",
    "scopegraphs-regular-expressions",
]
