[files]
include = [
    "src/concepts/*.rs",
    "examples/**/*.rs",
    "src/examples/*.rs",
]
root = "scopegraphs"

[parsing]
line_comment = [
    "///",
    "//",
    "//!",
]
block_comment = [
    [
        "/*",
        "*/",
        true,
    ],
    [
        "/**",
        "*/",
        true,
    ],
]
