[package]
name = "scopegraphs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scopegraphs-lib = {path="../scopegraphs-lib"}
scopegraphs-macros = {path="../scopegraphs-macros"}
scopegraphs-regular-expressions = {path="../scopegraphs-regular-expressions"}

[features]
default = ["dot"]
dot = ["scopegraphs-regular-expressions/dot", "scopegraphs-macros/dot"]