[package]
name = "scopegraphs"
version = "0.1.2"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = [
    "Aron Zwaan <A.S.Zwaan@tudelft.nl>",
    "Jonathan Dönszelmann <J.B.Doenszelmann@tudelft.nl>"
]
description = "A port of [scopegraphs](https://pl.ewi.tudelft.nl/research/projects/scope-graphs/) to Rust"
rust-version = "1.77"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scopegraphs-lib = { path = "../scopegraphs-lib", version = "0.1.0" }
scopegraphs-macros = { path = "../scopegraphs-macros", version = "0.1.0" }
scopegraphs-regular-expressions = { path = "../scopegraphs-regular-expressions", version = "0.1.0" }

[features]
default = ["dot", "dynamic-regex"]
dot = ["scopegraphs-regular-expressions/dot", "scopegraphs-macros/dot", "scopegraphs-lib/dot"]
dynamic-regex = ["scopegraphs-regular-expressions/dynamic"]
