[package]
name = "scopegraphs-regular-expressions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
syn = { version = "2.0.29", features = ["full", "extra-traits"] }
quote = { version = "1.0.33" , optional = true}
proc-macro2 = "1.0.69"
thiserror = "1.0.50"

[features]
rust-code-emitting = ["quote"]
pretty-print = ["quote"]
dot = ["pretty-print"]
