[package]
name = "scopegraphs-regular-expressions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
syn = { version = "2.0.29", features = ["full", "extra-traits"] }
quote = "1.0.33"
proc-macro2 = "1.0.69"
thiserror = "1.0.50"
regex = "1.10.2"
