[package]
name = "scopegraphs-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = "15.1.0"
scopegraphs-regular-expressions = {path = "../scopegraphs-regular-expressions"}

[dev-dependencies]
scopegraphs = {path = "../scopegraphs"}
