[package]
name = "scopegraphs-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = "3.14.0"
log = "0.4.20"
prust-lib = {git="https://github.com/jdonszelmann/prust", branch = "main"}
scopegraphs-regular-expressions = {path = "../scopegraphs-regular-expressions"}

[dev-dependencies]
scopegraphs = {path = "../scopegraphs"}
scopegraphs-macros = {path = "../scopegraphs-macros"}
env_logger = "0.10.1"
ctor = "0.2.5"
